const actions = [
    ,{'id': 0, 'name': 'CALL'},
    ,{'id': 1, 'name': 'SMS'}
]

const baseCustomers:Customer[] = [
    {'id': 2, 'msisdn': '251791207702', 'name' : 'Tekle Selamawit Getachew', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 66.56}
    ,{'id': 3, 'msisdn': '251719786753', 'name' : 'Tilahun Tadele Jemal', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 50.12}
    ,{'id': 4, 'msisdn': '251716521105', 'name' : 'Damtew Tekle Hailu', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'inactive', 'sixtyDay': 'inactive', 'ninetyDay': 'inactive'}, 'churnProbablity': 58.34}
    ,{'id': 5, 'msisdn': '251784503914', 'name' : 'Gebre Mekonnen Tekle', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 58.52}
    ,{'id': 6, 'msisdn': '251722416592', 'name' : 'Assefa Saba Tesfaye', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'inactive', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 24.97}
    ,{'id': 7, 'msisdn': '251753273107', 'name' : 'Negussie Tilahun Solomon', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 65.11}
    ,{'id': 8, 'msisdn': '251763988751', 'name' : 'Temesgen Getachew Tekle', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 25.77}
    ,{'id': 9, 'msisdn': '251721239388', 'name' : 'Haile Bekele Jemere', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 49.21}
    ,{'id': 10, 'msisdn': '251779117033', 'name' : 'Semira Assefa Kalkidan', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 44.0}
    ,{'id': 11, 'msisdn': '251745008838', 'name' : 'Teshome Fasil Tilahun', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 81.26}
    ,{'id': 12, 'msisdn': '251797442103', 'name' : 'Zerihun Damtew Gebremariam', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 30.64}
    ,{'id': 13, 'msisdn': '251779350389', 'name' : 'Lemlem Jemere Fekadu', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 48.32}
    ,{'id': 14, 'msisdn': '251712521706', 'name' : 'Ermias Woldemariam Reda', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 41.73}
    ,{'id': 15, 'msisdn': '251729301018', 'name' : 'Asnake Mengistu Lemlem', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 32.46}
    ,{'id': 16, 'msisdn': '251787395122', 'name' : 'Endale Asnake Asnake', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 51.05}
    ,{'id': 17, 'msisdn': '251781221489', 'name' : 'Desalegn Solomon Zewdu', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 42.42}
    ,{'id': 18, 'msisdn': '251744720191', 'name' : 'Lemma Woldemariam Zewdu', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 21.53}
    ,{'id': 19, 'msisdn': '251738697892', 'name' : 'Nigussie Lemma Haile', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 62.29}
    ,{'id': 20, 'msisdn': '251748864799', 'name' : 'Jemere Gebremariam Zerihun', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 66.17}
    ,{'id': 21, 'msisdn': '251798931712', 'name' : 'Lemma Tilahun Zerihun', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 11.23}
    ,{'id': 22, 'msisdn': '251765834261', 'name' : 'Dereje Biruk Hailu', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 21.71}
    ,{'id': 23, 'msisdn': '251737264870', 'name' : 'Nigist Endale Tilahun', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 27.23}
    ,{'id': 24, 'msisdn': '251743430821', 'name' : 'Negussie Kebede Zerihun', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'inactive', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 36.88}
    ,{'id': 25, 'msisdn': '251743386132', 'name' : 'Taye Tadesse Tesfaye', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 77.76}
    ,{'id': 26, 'msisdn': '251727140768', 'name' : 'Hailu Asrat Zerihun', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 87.05}
    ,{'id': 27, 'msisdn': '251712773323', 'name' : 'Mesfin Mulu Abera', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 56.34}
    ,{'id': 28, 'msisdn': '251789918206', 'name' : 'Hailu Dinku Lemma', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'inactive', 'sixtyDay': 'inactive', 'ninetyDay': 'active'}, 'churnProbablity': 30.1}
    ,{'id': 29, 'msisdn': '251743354907', 'name' : 'Negussie Endale Desalegn', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 16.64}
    ,{'id': 30, 'msisdn': '251741463095', 'name' : 'Tesfaye Mengistu Haile', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 15.52}
    ,{'id': 31, 'msisdn': '251733401375', 'name' : 'Negussie Fasil Solomon', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 20.46}
    ,{'id': 32, 'msisdn': '251731964223', 'name' : 'Yetbarek Yetbarek Biruk', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 19.5}
    ,{'id': 33, 'msisdn': '251772454567', 'name' : 'Moges Gebremariam Reda', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 86.48}
    ,{'id': 34, 'msisdn': '251745043463', 'name' : 'Tadesse Tadesse Teshome', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 38.9}
    ,{'id': 35, 'msisdn': '251783767941', 'name' : 'Teshome Tadesse Gebre', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 28.74}
    ,{'id': 36, 'msisdn': '251718248136', 'name' : 'Reda Lemma Desalegn', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 45.29}
    ,{'id': 37, 'msisdn': '251753368367', 'name' : 'Hailu Gebre Negussie', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 33.15}
    ,{'id': 38, 'msisdn': '251751309527', 'name' : 'Tadesse Lemma Woldemariam', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 15.77}
    ,{'id': 39, 'msisdn': '251770022709', 'name' : 'Demeke Haile Kebede', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'inactive', 'sixtyDay': 'inactive', 'ninetyDay': 'inactive'}, 'churnProbablity': 70.44}
    ,{'id': 40, 'msisdn': '251796853910', 'name' : 'Tilahun Gebremedhin Yonas', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 36.01}
    ,{'id': 41, 'msisdn': '251774876698', 'name' : 'Berhane Weldemichael Woldemariam', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 54.65}
    ,{'id': 42, 'msisdn': '251756455085', 'name' : 'Weldemichael Fekadu Nebiyu', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 41.47}
    ,{'id': 43, 'msisdn': '251768873192', 'name' : 'Negussie Gebre Tadele', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 38.2}
    ,{'id': 44, 'msisdn': '251728656517', 'name' : 'Gebremariam Berhanu Dereje', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 25.26}
    ,{'id': 45, 'msisdn': '251727806724', 'name' : 'Teshome Natnael Selamawit', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 30.98}
    ,{'id': 46, 'msisdn': '251721621985', 'name' : 'Berhane Lemma Zewdu', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 49.28}
    ,{'id': 47, 'msisdn': '251717012030', 'name' : 'Gebre Weldemichael Jemal', 'status': {'daily': 'active', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 83.58}
    ,{'id': 48, 'msisdn': '251778852833', 'name' : 'Negussie Damtew Woldemariam', 'status': {'daily': 'inactive', 'weekly': 'inactive', 'thirtyDay' :  'inactive', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 19.15}
    ,{'id': 49, 'msisdn': '251714690067', 'name' : 'Teshome Mengistu Belete', 'status': {'daily': 'inactive', 'weekly': 'active', 'thirtyDay' :  'active', 'sixtyDay': 'active', 'ninetyDay': 'active'}, 'churnProbablity': 68.28}
]
const baseLinks = [
    {'source': '4', 'target': '46', 'label': 'SENT_SMS'},
    {'source': '44', 'target': '51', 'label': 'CALLED'},
    {'source': '13', 'target': '21', 'label': 'SENT_SMS'},
    {'source': '16', 'target': '29', 'label': 'CALLED'},
    {'source': '18', 'target': '13', 'label': 'SENT_SMS'},
    {'source': '49', 'target': '31', 'label': 'SENT_SMS'},
    {'source': '53', 'target': '45', 'label': 'CALLED'},
    {'source': '31', 'target': '33', 'label': 'SENT_SMS'},
    {'source': '43', 'target': '22', 'label': 'SENT_SMS'},
    {'source': '4', 'target': '18', 'label': 'SENT_SMS'},
    {'source': '36', 'target': '20', 'label': 'SENT_SMS'},
    {'source': '15', 'target': '4', 'label': 'CALLED'},
    {'source': '7', 'target': '23', 'label': 'SENT_SMS'},
    {'source': '12', 'target': '21', 'label': 'CALLED'},
    {'source': '50', 'target': '42', 'label': 'SENT_SMS'},
    {'source': '48', 'target': '32', 'label': 'SENT_SMS'},
    {'source': '36', 'target': '48', 'label': 'SENT_SMS'},
    {'source': '48', 'target': '12', 'label': 'SENT_SMS'},
    {'source': '8', 'target': '40', 'label': 'SENT_SMS'},
    {'source': '8', 'target': '32', 'label': 'CALLED'},
    {'source': '12', 'target': '12', 'label': 'SENT_SMS'},
    {'source': '44', 'target': '60', 'label': 'SENT_SMS'},
    {'source': '4', 'target': '44', 'label': 'SENT_SMS'},
    {'source': '60', 'target': '5', 'label': 'CALLED'},
    {'source': '55', 'target': '30', 'label': 'SENT_SMS'},
    {'source': '14', 'target': '19', 'label': 'SENT_SMS'},
    {'source': '21', 'target': '51', 'label': 'SENT_SMS'},
    {'source': '28', 'target': '17', 'label': 'CALLED'},
    {'source': '10', 'target': '26', 'label': 'SENT_SMS'},
    {'source': '34', 'target': '51', 'label': 'CALLED'},
    {'source': '40', 'target': '27', 'label': 'SENT_SMS'},
    {'source': '37', 'target': '23', 'label': 'SENT_SMS'},
    {'source': '36', 'target': '12', 'label': 'SENT_SMS'},
    {'source': '23', 'target': '27', 'label': 'CALLED'},
    {'source': '10', 'target': '53', 'label': 'CALLED'},
    {'source': '18', 'target': '20', 'label': 'CALLED'},
    {'source': '60', 'target': '11', 'label': 'SENT_SMS'},
    {'source': '27', 'target': '51', 'label': 'CALLED'},
    {'source': '32', 'target': '6', 'label': 'SENT_SMS'},
    {'source': '50', 'target': '31', 'label': 'CALLED'},
    {'source': '8', 'target': '21', 'label': 'SENT_SMS'},
    {'source': '8', 'target': '23', 'label': 'SENT_SMS'},
    {'source': '24', 'target': '17', 'label': 'CALLED'},
    {'source': '39', 'target': '4', 'label': 'SENT_SMS'},
    {'source': '46', 'target': '8', 'label': 'CALLED'},
    {'source': '29', 'target': '38', 'label': 'SENT_SMS'},
    {'source': '33', 'target': '2', 'label': 'SENT_SMS'},
    {'source': '29', 'target': '46', 'label': 'SENT_SMS'},
    {'source': '23', 'target': '29', 'label': 'CALLED'},
    {'source': '17', 'target': '59', 'label': 'SENT_SMS'},
    {'source': '27', 'target': '30', 'label': 'CALLED'},
    {'source': '30', 'target': '38', 'label': 'SENT_SMS'},
    {'source': '3', 'target': '52', 'label': 'CALLED'},
    {'source': '10', 'target': '56', 'label': 'SENT_SMS'},
    {'source': '37', 'target': '11', 'label': 'SENT_SMS'},
    {'source': '11', 'target': '56', 'label': 'SENT_SMS'},
    {'source': '7', 'target': '42', 'label': 'CALLED'},
    {'source': '51', 'target': '20', 'label': 'SENT_SMS'},
    {'source': '20', 'target': '33', 'label': 'CALLED'},
    {'source': '18', 'target': '48', 'label': 'CALLED'},
    {'source': '6', 'target': '42', 'label': 'SENT_SMS'},
    {'source': '47', 'target': '56', 'label': 'CALLED'},
    {'source': '32', 'target': '16', 'label': 'CALLED'},
    {'source': '19', 'target': '34', 'label': 'SENT_SMS'},
    {'source': '40', 'target': '22', 'label': 'CALLED'},
    {'source': '19', 'target': '22', 'label': 'SENT_SMS'},
    {'source': '22', 'target': '56', 'label': 'CALLED'},
    {'source': '30', 'target': '38', 'label': 'SENT_SMS'},
    {'source': '36', 'target': '37', 'label': 'CALLED'},
    {'source': '6', 'target': '5', 'label': 'CALLED'},
    {'source': '32', 'target': '49', 'label': 'SENT_SMS'},
    {'source': '30', 'target': '46', 'label': 'CALLED'},
    {'source': '32', 'target': '14', 'label': 'SENT_SMS'},
    {'source': '3', 'target': '50', 'label': 'SENT_SMS'},
    {'source': '27', 'target': '8', 'label': 'CALLED'},
    {'source': '50', 'target': '13', 'label': 'CALLED'},
    {'source': '21', 'target': '7', 'label': 'CALLED'},
    {'source': '10', 'target': '32', 'label': 'CALLED'},
    {'source': '2', 'target': '43', 'label': 'CALLED'},
    {'source': '30', 'target': '50', 'label': 'CALLED'},
    {'source': '22', 'target': '26', 'label': 'SENT_SMS'},
    {'source': '43', 'target': '20', 'label': 'CALLED'},
    {'source': '19', 'target': '10', 'label': 'SENT_SMS'},
    {'source': '25', 'target': '35', 'label': 'SENT_SMS'},
    {'source': '45', 'target': '18', 'label': 'SENT_SMS'},
    {'source': '54', 'target': '56', 'label': 'SENT_SMS'},
    {'source': '54', 'target': '6', 'label': 'CALLED'},
    {'source': '41', 'target': '58', 'label': 'CALLED'},
    {'source': '47', 'target': '24', 'label': 'CALLED'},
    {'source': '42', 'target': '37', 'label': 'CALLED'},
    {'source': '51', 'target': '46', 'label': 'SENT_SMS'},
    {'source': '60', 'target': '9', 'label': 'SENT_SMS'},
    {'source': '10', 'target': '12', 'label': 'CALLED'},
    {'source': '28', 'target': '53', 'label': 'CALLED'},
    {'source': '39', 'target': '33', 'label': 'SENT_SMS'},
    {'source': '18', 'target': '3', 'label': 'SENT_SMS'},
    {'source': '33', 'target': '7', 'label': 'SENT_SMS'},
    {'source': '56', 'target': '38', 'label': 'CALLED'},
    {'source': '20', 'target': '20', 'label': 'SENT_SMS'},
    {'source': '24', 'target': '17', 'label': 'CALLED'},
    {'source': '18', 'target': '18', 'label': 'CALLED'},
    {'source': '36', 'target': '24', 'label': 'CALLED'},
    {'source': '57', 'target': '26', 'label': 'CALLED'},
    {'source': '5', 'target': '3', 'label': 'SENT_SMS'},
    {'source': '33', 'target': '24', 'label': 'CALLED'},
    {'source': '46', 'target': '28', 'label': 'CALLED'},
    {'source': '26', 'target': '58', 'label': 'CALLED'},
    {'source': '9', 'target': '23', 'label': 'SENT_SMS'},
    {'source': '55', 'target': '42', 'label': 'CALLED'},
    {'source': '50', 'target': '10', 'label': 'CALLED'},
    {'source': '2', 'target': '44', 'label': 'SENT_SMS'},
    {'source': '57', 'target': '27', 'label': 'CALLED'},
    {'source': '25', 'target': '45', 'label': 'SENT_SMS'},
    {'source': '3', 'target': '6', 'label': 'CALLED'},
    {'source': '36', 'target': '45', 'label': 'SENT_SMS'},
    {'source': '28', 'target': '19', 'label': 'SENT_SMS'},
    {'source': '27', 'target': '29', 'label': 'CALLED'},
    {'source': '55', 'target': '23', 'label': 'CALLED'},
    {'source': '9', 'target': '45', 'label': 'CALLED'},
    {'source': '36', 'target': '24', 'label': 'CALLED'},
    {'source': '16', 'target': '56', 'label': 'SENT_SMS'},
    {'source': '3', 'target': '28', 'label': 'SENT_SMS'},
    {'source': '18', 'target': '3', 'label': 'CALLED'},
    {'source': '18', 'target': '44', 'label': 'CALLED'},
    {'source': '25', 'target': '4', 'label': 'CALLED'},
    {'source': '26', 'target': '8', 'label': 'SENT_SMS'},
    {'source': '12', 'target': '33', 'label': 'SENT_SMS'},
    {'source': '41', 'target': '51', 'label': 'SENT_SMS'},
    {'source': '6', 'target': '13', 'label': 'CALLED'},
    {'source': '45', 'target': '56', 'label': 'SENT_SMS'},
    {'source': '43', 'target': '23', 'label': 'CALLED'},
    {'source': '4', 'target': '44', 'label': 'SENT_SMS'},
    {'source': '32', 'target': '23', 'label': 'SENT_SMS'},
    {'source': '32', 'target': '26', 'label': 'SENT_SMS'},
    {'source': '40', 'target': '45', 'label': 'CALLED'},
    {'source': '9', 'target': '5', 'label': 'CALLED'},
    {'source': '50', 'target': '33', 'label': 'CALLED'},
    {'source': '21', 'target': '41', 'label': 'CALLED'},
    {'source': '32', 'target': '48', 'label': 'SENT_SMS'},
    {'source': '51', 'target': '20', 'label': 'SENT_SMS'},
    {'source': '20', 'target': '46', 'label': 'CALLED'},
    {'source': '33', 'target': '19', 'label': 'CALLED'},
    {'source': '12', 'target': '28', 'label': 'SENT_SMS'},
    {'source': '12', 'target': '42', 'label': 'SENT_SMS'},
    {'source': '14', 'target': '4', 'label': 'CALLED'},
    {'source': '12', 'target': '26', 'label': 'SENT_SMS'},
    {'source': '53', 'target': '58', 'label': 'SENT_SMS'},
    {'source': '32', 'target': '58', 'label': 'CALLED'},
    {'source': '51', 'target': '36', 'label': 'SENT_SMS'},
    {'source': '38', 'target': '56', 'label': 'SENT_SMS'},
    {'source': '6', 'target': '18', 'label': 'SENT_SMS'},
    {'source': '10', 'target': '11', 'label': 'SENT_SMS'},
    {'source': '52', 'target': '23', 'label': 'SENT_SMS'},
    {'source': '44', 'target': '9', 'label': 'CALLED'},
    {'source': '5', 'target': '18', 'label': 'SENT_SMS'},
    {'source': '52', 'target': '53', 'label': 'CALLED'},
    {'source': '35', 'target': '35', 'label': 'SENT_SMS'},
    {'source': '17', 'target': '18', 'label': 'CALLED'},
    {'source': '11', 'target': '26', 'label': 'CALLED'},
    {'source': '54', 'target': '46', 'label': 'SENT_SMS'},
    {'source': '32', 'target': '15', 'label': 'CALLED'},
    {'source': '58', 'target': '41', 'label': 'SENT_SMS'},
    {'source': '14', 'target': '23', 'label': 'CALLED'},
    {'source': '2', 'target': '34', 'label': 'CALLED'},
    {'source': '5', 'target': '28', 'label': 'CALLED'},
    {'source': '24', 'target': '52', 'label': 'SENT_SMS'},
    {'source': '49', 'target': '32', 'label': 'SENT_SMS'},
    {'source': '35', 'target': '48', 'label': 'SENT_SMS'},
    {'source': '42', 'target': '32', 'label': 'SENT_SMS'},
    {'source': '50', 'target': '45', 'label': 'SENT_SMS'},
    {'source': '58', 'target': '34', 'label': 'SENT_SMS'},
    {'source': '24', 'target': '17', 'label': 'SENT_SMS'},
    {'source': '39', 'target': '12', 'label': 'CALLED'},
    {'source': '36', 'target': '59', 'label': 'SENT_SMS'},
    {'source': '20', 'target': '18', 'label': 'CALLED'},
    {'source': '52', 'target': '13', 'label': 'SENT_SMS'},
    {'source': '21', 'target': '59', 'label': 'CALLED'},
    {'source': '54', 'target': '52', 'label': 'CALLED'},
    {'source': '21', 'target': '60', 'label': 'CALLED'},
    {'source': '54', 'target': '27', 'label': 'CALLED'},
    {'source': '59', 'target': '29', 'label': 'CALLED'},
    {'source': '26', 'target': '54', 'label': 'SENT_SMS'},
    {'source': '39', 'target': '16', 'label': 'CALLED'},
    {'source': '15', 'target': '38', 'label': 'SENT_SMS'},
    {'source': '42', 'target': '56', 'label': 'SENT_SMS'},
    {'source': '47', 'target': '2', 'label': 'SENT_SMS'},
    {'source': '57', 'target': '58', 'label': 'CALLED'},
    {'source': '8', 'target': '25', 'label': 'CALLED'},
    {'source': '48', 'target': '7', 'label': 'CALLED'},
    {'source': '25', 'target': '11', 'label': 'CALLED'},
    {'source': '23', 'target': '15', 'label': 'SENT_SMS'},
    {'source': '43', 'target': '22', 'label': 'SENT_SMS'},
    {'source': '46', 'target': '22', 'label': 'SENT_SMS'},
    {'source': '52', 'target': '25', 'label': 'SENT_SMS'},
    {'source': '49', 'target': '54', 'label': 'CALLED'},
    {'source': '38', 'target': '3', 'label': 'SENT_SMS'},
    {'source': '25', 'target': '15', 'label': 'SENT_SMS'},
    {'source': '39', 'target': '22', 'label': 'SENT_SMS'},
    {'source': '5', 'target': '29', 'label': 'CALLED'},
    {'source': '12', 'target': '24', 'label': 'SENT_SMS'},
    {'source': '12', 'target': '37', 'label': 'CALLED'},
    {'source': '2', 'target': '35', 'label': 'CALLED'},
    {'source': '56', 'target': '29', 'label': 'CALLED'},
    {'source': '4', 'target': '60', 'label': 'CALLED'},
    {'source': '49', 'target': '35', 'label': 'SENT_SMS'},
    {'source': '29', 'target': '15', 'label': 'CALLED'},
    {'source': '44', 'target': '18', 'label': 'SENT_SMS'},
    {'source': '48', 'target': '60', 'label': 'SENT_SMS'},
    {'source': '37', 'target': '55', 'label': 'SENT_SMS'},
    {'source': '48', 'target': '15', 'label': 'SENT_SMS'},
    {'source': '30', 'target': '9', 'label': 'CALLED'},
    {'source': '21', 'target': '7', 'label': 'SENT_SMS'},
    {'source': '32', 'target': '28', 'label': 'CALLED'},
    {'source': '56', 'target': '6', 'label': 'CALLED'},
    {'source': '21', 'target': '59', 'label': 'SENT_SMS'},
    {'source': '35', 'target': '15', 'label': 'SENT_SMS'},
    {'source': '21', 'target': '25', 'label': 'CALLED'},
    {'source': '59', 'target': '29', 'label': 'SENT_SMS'},
    {'source': '32', 'target': '29', 'label': 'SENT_SMS'},
    {'source': '26', 'target': '43', 'label': 'CALLED'},
    {'source': '52', 'target': '15', 'label': 'CALLED'},
    {'source': '19', 'target': '39', 'label': 'SENT_SMS'},
    {'source': '23', 'target': '44', 'label': 'CALLED'},
    {'source': '51', 'target': '56', 'label': 'SENT_SMS'},
    {'source': '18', 'target': '11', 'label': 'SENT_SMS'},
    {'source': '54', 'target': '44', 'label': 'CALLED'},
    {'source': '12', 'target': '9', 'label': 'SENT_SMS'},
    {'source': '24', 'target': '14', 'label': 'SENT_SMS'},
    {'source': '37', 'target': '48', 'label': 'CALLED'},
    {'source': '9', 'target': '40', 'label': 'CALLED'},
    {'source': '39', 'target': '8', 'label': 'SENT_SMS'},
    {'source': '10', 'target': '18', 'label': 'SENT_SMS'},
    {'source': '59', 'target': '57', 'label': 'SENT_SMS'},
    {'source': '50', 'target': '58', 'label': 'SENT_SMS'},
    {'source': '14', 'target': '42', 'label': 'SENT_SMS'},
    {'source': '43', 'target': '60', 'label': 'SENT_SMS'},
    {'source': '37', 'target': '48', 'label': 'SENT_SMS'},
    {'source': '29', 'target': '15', 'label': 'CALLED'},
    {'source': '32', 'target': '27', 'label': 'SENT_SMS'},
    {'source': '4', 'target': '43', 'label': 'CALLED'},
    {'source': '42', 'target': '39', 'label': 'CALLED'},
    {'source': '33', 'target': '2', 'label': 'SENT_SMS'},
    {'source': '11', 'target': '30', 'label': 'SENT_SMS'},
    {'source': '34', 'target': '44', 'label': 'CALLED'},
    {'source': '5', 'target': '28', 'label': 'CALLED'},
    {'source': '18', 'target': '45', 'label': 'SENT_SMS'},
    {'source': '29', 'target': '18', 'label': 'SENT_SMS'},
    {'source': '38', 'target': '21', 'label': 'CALLED'},
    {'source': '19', 'target': '53', 'label': 'CALLED'},
    {'source': '18', 'target': '27', 'label': 'SENT_SMS'},
    {'source': '31', 'target': '40', 'label': 'SENT_SMS'},
    {'source': '21', 'target': '50', 'label': 'SENT_SMS'},
    {'source': '53', 'target': '59', 'label': 'SENT_SMS'},
    {'source': '52', 'target': '14', 'label': 'SENT_SMS'},
    {'source': '32', 'target': '9', 'label': 'CALLED'},
    {'source': '44', 'target': '17', 'label': 'SENT_SMS'},
    {'source': '56', 'target': '58', 'label': 'CALLED'},
    {'source': '8', 'target': '47', 'label': 'SENT_SMS'},
    {'source': '57', 'target': '58', 'label': 'CALLED'},
    {'source': '51', 'target': '52', 'label': 'SENT_SMS'},
    {'source': '48', 'target': '41', 'label': 'CALLED'},
    {'source': '33', 'target': '13', 'label': 'CALLED'},
    {'source': '52', 'target': '19', 'label': 'CALLED'},
    {'source': '46', 'target': '44', 'label': 'SENT_SMS'},
    {'source': '34', 'target': '34', 'label': 'SENT_SMS'},
    {'source': '57', 'target': '44', 'label': 'CALLED'},
    {'source': '9', 'target': '5', 'label': 'SENT_SMS'},
    {'source': '56', 'target': '27', 'label': 'SENT_SMS'},
    {'source': '21', 'target': '28', 'label': 'CALLED'},
    {'source': '48', 'target': '40', 'label': 'CALLED'},
    {'source': '29', 'target': '38', 'label': 'SENT_SMS'},
    {'source': '45', 'target': '17', 'label': 'SENT_SMS'},
    {'source': '51', 'target': '54', 'label': 'SENT_SMS'},
    {'source': '59', 'target': '13', 'label': 'SENT_SMS'},
    {'source': '59', 'target': '18', 'label': 'CALLED'},
    {'source': '7', 'target': '42', 'label': 'CALLED'},
    {'source': '4', 'target': '34', 'label': 'SENT_SMS'},
    {'source': '26', 'target': '24', 'label': 'CALLED'},
    {'source': '14', 'target': '56', 'label': 'SENT_SMS'},
    {'source': '34', 'target': '16', 'label': 'SENT_SMS'},
    {'source': '23', 'target': '2', 'label': 'CALLED'},
    {'source': '5', 'target': '31', 'label': 'SENT_SMS'},
    {'source': '42', 'target': '40', 'label': 'SENT_SMS'},
    {'source': '52', 'target': '31', 'label': 'CALLED'},
    {'source': '46', 'target': '55', 'label': 'SENT_SMS'},
    {'source': '54', 'target': '41', 'label': 'SENT_SMS'},
    {'source': '14', 'target': '33', 'label': 'CALLED'},
    {'source': '11', 'target': '15', 'label': 'CALLED'},
    {'source': '58', 'target': '18', 'label': 'CALLED'},
    {'source': '28', 'target': '29', 'label': 'SENT_SMS'},
    {'source': '30', 'target': '51', 'label': 'CALLED'},
    {'source': '11', 'target': '60', 'label': 'CALLED'},
    {'source': '45', 'target': '15', 'label': 'CALLED'},
    {'source': '50', 'target': '10', 'label': 'SENT_SMS'},
    {'source': '13', 'target': '60', 'label': 'SENT_SMS'},
    {'source': '24', 'target': '39', 'label': 'CALLED'},
    {'source': '49', 'target': '36', 'label': 'CALLED'},
    {'source': '46', 'target': '5', 'label': 'SENT_SMS'},
    {'source': '8', 'target': '25', 'label': 'SENT_SMS'},
    {'source': '55', 'target': '2', 'label': 'CALLED'},
    {'source': '45', 'target': '45', 'label': 'CALLED'},
    {'source': '10', 'target': '54', 'label': 'SENT_SMS'},
    {'source': '57', 'target': '25', 'label': 'CALLED'},
    {'source': '18', 'target': '43', 'label': 'CALLED'},
    {'source': '43', 'target': '38', 'label': 'SENT_SMS'},
    {'source': '7', 'target': '11', 'label': 'CALLED'},
    {'source': '59', 'target': '42', 'label': 'CALLED'},
    {'source': '51', 'target': '40', 'label': 'SENT_SMS'},
    {'source': '7', 'target': '58', 'label': 'SENT_SMS'},
    {'source': '29', 'target': '41', 'label': 'CALLED'},
    {'source': '53', 'target': '59', 'label': 'CALLED'},
    {'source': '10', 'target': '34', 'label': 'SENT_SMS'},
    {'source': '14', 'target': '43', 'label': 'SENT_SMS'},
    {'source': '3', 'target': '9', 'label': 'CALLED'},
    {'source': '4', 'target': '25', 'label': 'CALLED'},
    {'source': '35', 'target': '56', 'label': 'CALLED'},
    {'source': '9', 'target': '60', 'label': 'SENT_SMS'},
    {'source': '7', 'target': '5', 'label': 'SENT_SMS'},
    {'source': '59', 'target': '11', 'label': 'CALLED'},
    {'source': '6', 'target': '4', 'label': 'SENT_SMS'},
    {'source': '52', 'target': '55', 'label': 'CALLED'},
    {'source': '10', 'target': '43', 'label': 'CALLED'},
    {'source': '45', 'target': '48', 'label': 'CALLED'},
    {'source': '32', 'target': '37', 'label': 'CALLED'},
    {'source': '20', 'target': '45', 'label': 'CALLED'},
    {'source': '57', 'target': '48', 'label': 'SENT_SMS'},
    {'source': '31', 'target': '36', 'label': 'SENT_SMS'},
    {'source': '55', 'target': '54', 'label': 'SENT_SMS'},
    {'source': '21', 'target': '39', 'label': 'SENT_SMS'},
    {'source': '31', 'target': '6', 'label': 'CALLED'},
    {'source': '36', 'target': '55', 'label': 'SENT_SMS'},
    {'source': '29', 'target': '32', 'label': 'SENT_SMS'},
    {'source': '42', 'target': '59', 'label': 'CALLED'},
    {'source': '6', 'target': '3', 'label': 'CALLED'},
    {'source': '23', 'target': '50', 'label': 'SENT_SMS'},
    {'source': '29', 'target': '36', 'label': 'CALLED'},
    {'source': '58', 'target': '60', 'label': 'CALLED'},
    {'source': '60', 'target': '20', 'label': 'CALLED'},
    {'source': '45', 'target': '31', 'label': 'SENT_SMS'},
    {'source': '22', 'target': '39', 'label': 'SENT_SMS'},
    {'source': '20', 'target': '36', 'label': 'CALLED'},
    {'source': '27', 'target': '44', 'label': 'CALLED'},
    {'source': '59', 'target': '46', 'label': 'CALLED'},
    {'source': '7', 'target': '7', 'label': 'SENT_SMS'},
    {'source': '18', 'target': '21', 'label': 'SENT_SMS'},
    {'source': '57', 'target': '8', 'label': 'CALLED'},
    {'source': '40', 'target': '30', 'label': 'CALLED'},
    {'source': '17', 'target': '41', 'label': 'CALLED'},
    {'source': '34', 'target': '15', 'label': 'CALLED'},
    {'source': '26', 'target': '15', 'label': 'SENT_SMS'},
    {'source': '8', 'target': '49', 'label': 'CALLED'},
    {'source': '23', 'target': '49', 'label': 'SENT_SMS'},
    {'source': '10', 'target': '13', 'label': 'SENT_SMS'},
    {'source': '21', 'target': '58', 'label': 'CALLED'},
    {'source': '50', 'target': '15', 'label': 'CALLED'},
    {'source': '47', 'target': '47', 'label': 'CALLED'},
    {'source': '49', 'target': '2', 'label': 'CALLED'},
    {'source': '44', 'target': '32', 'label': 'CALLED'},
    {'source': '39', 'target': '11', 'label': 'SENT_SMS'},
    {'source': '16', 'target': '35', 'label': 'CALLED'},
    {'source': '2', 'target': '38', 'label': 'CALLED'},
    {'source': '29', 'target': '32', 'label': 'CALLED'},
    {'source': '36', 'target': '32', 'label': 'SENT_SMS'},
    {'source': '50', 'target': '8', 'label': 'SENT_SMS'},
    {'source': '49', 'target': '24', 'label': 'SENT_SMS'},
    {'source': '48', 'target': '40', 'label': 'CALLED'},
    {'source': '37', 'target': '21', 'label': 'SENT_SMS'},
    {'source': '51', 'target': '42', 'label': 'CALLED'},
    {'source': '60', 'target': '16', 'label': 'SENT_SMS'},
    {'source': '46', 'target': '12', 'label': 'SENT_SMS'},
    {'source': '56', 'target': '53', 'label': 'CALLED'},
    {'source': '14', 'target': '7', 'label': 'SENT_SMS'},
    {'source': '55', 'target': '23', 'label': 'SENT_SMS'},
    {'source': '60', 'target': '30', 'label': 'SENT_SMS'},
    {'source': '44', 'target': '32', 'label': 'CALLED'},
    {'source': '12', 'target': '19', 'label': 'SENT_SMS'},
    {'source': '32', 'target': '56', 'label': 'CALLED'},
    {'source': '19', 'target': '26', 'label': 'CALLED'},
    {'source': '2', 'target': '32', 'label': 'SENT_SMS'},
    {'source': '58', 'target': '59', 'label': 'SENT_SMS'},
    {'source': '7', 'target': '23', 'label': 'SENT_SMS'},
    {'source': '11', 'target': '21', 'label': 'CALLED'},
    {'source': '17', 'target': '6', 'label': 'SENT_SMS'},
    {'source': '39', 'target': '5', 'label': 'SENT_SMS'},
    {'source': '40', 'target': '22', 'label': 'CALLED'},
    {'source': '50', 'target': '51', 'label': 'CALLED'},
    {'source': '59', 'target': '53', 'label': 'CALLED'},
    {'source': '5', 'target': '59', 'label': 'CALLED'},
    {'source': '37', 'target': '15', 'label': 'SENT_SMS'},
    {'source': '59', 'target': '46', 'label': 'SENT_SMS'},
    {'source': '19', 'target': '49', 'label': 'CALLED'},
    {'source': '9', 'target': '42', 'label': 'CALLED'},
    {'source': '56', 'target': '60', 'label': 'SENT_SMS'},
    {'source': '2', 'target': '24', 'label': 'SENT_SMS'},
    {'source': '31', 'target': '29', 'label': 'CALLED'},
    {'source': '10', 'target': '37', 'label': 'CALLED'},
    {'source': '6', 'target': '20', 'label': 'CALLED'},
    {'source': '36', 'target': '50', 'label': 'CALLED'},
    {'source': '26', 'target': '15', 'label': 'CALLED'},
    {'source': '20', 'target': '50', 'label': 'SENT_SMS'},
    {'source': '15', 'target': '50', 'label': 'SENT_SMS'},
    {'source': '26', 'target': '44', 'label': 'CALLED'},
    {'source': '35', 'target': '4', 'label': 'SENT_SMS'},
    {'source': '29', 'target': '39', 'label': 'CALLED'},
    {'source': '7', 'target': '34', 'label': 'CALLED'},
    {'source': '38', 'target': '58', 'label': 'CALLED'},
    {'source': '56', 'target': '33', 'label': 'CALLED'},
    {'source': '14', 'target': '13', 'label': 'SENT_SMS'},
    {'source': '4', 'target': '34', 'label': 'SENT_SMS'},
    {'source': '32', 'target': '40', 'label': 'SENT_SMS'},
    {'source': '7', 'target': '60', 'label': 'CALLED'},
    {'source': '30', 'target': '20', 'label': 'SENT_SMS'},
    {'source': '25', 'target': '36', 'label': 'CALLED'},
    {'source': '3', 'target': '60', 'label': 'CALLED'},
    {'source': '8', 'target': '56', 'label': 'SENT_SMS'},
    {'source': '14', 'target': '4', 'label': 'SENT_SMS'},
    {'source': '36', 'target': '10', 'label': 'CALLED'},
    {'source': '15', 'target': '43', 'label': 'CALLED'},
    {'source': '6', 'target': '60', 'label': 'CALLED'},
    {'source': '3', 'target': '30', 'label': 'CALLED'},
    {'source': '7', 'target': '25', 'label': 'SENT_SMS'},
    {'source': '39', 'target': '18', 'label': 'SENT_SMS'},
    {'source': '46', 'target': '54', 'label': 'CALLED'},
    {'source': '16', 'target': '48', 'label': 'CALLED'},
    {'source': '44', 'target': '30', 'label': 'SENT_SMS'},
    {'source': '23', 'target': '53', 'label': 'CALLED'},
    {'source': '51', 'target': '60', 'label': 'CALLED'},
    {'source': '9', 'target': '26', 'label': 'CALLED'},
    {'source': '50', 'target': '54', 'label': 'CALLED'},
    {'source': '60', 'target': '13', 'label': 'SENT_SMS'},
    {'source': '45', 'target': '26', 'label': 'CALLED'},
    {'source': '45', 'target': '24', 'label': 'SENT_SMS'},
    {'source': '44', 'target': '15', 'label': 'SENT_SMS'},
    {'source': '18', 'target': '29', 'label': 'CALLED'},
    {'source': '11', 'target': '46', 'label': 'CALLED'},
    {'source': '10', 'target': '58', 'label': 'CALLED'},
    {'source': '39', 'target': '49', 'label': 'SENT_SMS'},
    {'source': '48', 'target': '57', 'label': 'SENT_SMS'},
    {'source': '54', 'target': '43', 'label': 'SENT_SMS'},
    {'source': '4', 'target': '25', 'label': 'CALLED'},
    {'source': '19', 'target': '24', 'label': 'SENT_SMS'},
    {'source': '50', 'target': '46', 'label': 'SENT_SMS'},
    {'source': '44', 'target': '12', 'label': 'CALLED'},
    {'source': '57', 'target': '34', 'label': 'CALLED'},
    {'source': '59', 'target': '36', 'label': 'SENT_SMS'},
    {'source': '23', 'target': '54', 'label': 'SENT_SMS'},
    {'source': '42', 'target': '22', 'label': 'SENT_SMS'},
    {'source': '17', 'target': '2', 'label': 'SENT_SMS'},
    {'source': '27', 'target': '31', 'label': 'CALLED'},
    {'source': '6', 'target': '4', 'label': 'SENT_SMS'},
    {'source': '18', 'target': '17', 'label': 'CALLED'},
    {'source': '47', 'target': '38', 'label': 'CALLED'},
    {'source': '20', 'target': '33', 'label': 'CALLED'},
    {'source': '49', 'target': '57', 'label': 'CALLED'},
    {'source': '23', 'target': '11', 'label': 'CALLED'},
    {'source': '45', 'target': '48', 'label': 'CALLED'},
    {'source': '14', 'target': '17', 'label': 'SENT_SMS'},
    {'source': '54', 'target': '24', 'label': 'CALLED'},
    {'source': '11', 'target': '58', 'label': 'CALLED'},
    {'source': '9', 'target': '32', 'label': 'SENT_SMS'},
    {'source': '54', 'target': '35', 'label': 'CALLED'},
    {'source': '4', 'target': '11', 'label': 'SENT_SMS'},
    {'source': '57', 'target': '8', 'label': 'SENT_SMS'},
    {'source': '2', 'target': '16', 'label': 'SENT_SMS'},
    {'source': '60', 'target': '26', 'label': 'CALLED'},
    {'source': '23', 'target': '34', 'label': 'SENT_SMS'},
    {'source': '21', 'target': '36', 'label': 'CALLED'},
    {'source': '24', 'target': '22', 'label': 'CALLED'},
    {'source': '3', 'target': '33', 'label': 'CALLED'},
    {'source': '34', 'target': '28', 'label': 'CALLED'},
    {'source': '2', 'target': '42', 'label': 'SENT_SMS'},
    {'source': '14', 'target': '27', 'label': 'SENT_SMS'},
    {'source': '24', 'target': '4', 'label': 'CALLED'},
    {'source': '40', 'target': '9', 'label': 'CALLED'},
    {'source': '29', 'target': '36', 'label': 'SENT_SMS'},
    {'source': '50', 'target': '29', 'label': 'SENT_SMS'},
    {'source': '53', 'target': '55', 'label': 'SENT_SMS'},
    {'source': '52', 'target': '20', 'label': 'SENT_SMS'},
    {'source': '21', 'target': '17', 'label': 'SENT_SMS'},
    {'source': '45', 'target': '20', 'label': 'SENT_SMS'},
    {'source': '59', 'target': '42', 'label': 'CALLED'},
    {'source': '22', 'target': '5', 'label': 'SENT_SMS'},
    {'source': '19', 'target': '25', 'label': 'SENT_SMS'},
    {'source': '21', 'target': '32', 'label': 'SENT_SMS'},
    {'source': '16', 'target': '14', 'label': 'SENT_SMS'},
    {'source': '49', 'target': '21', 'label': 'CALLED'},
    {'source': '28', 'target': '20', 'label': 'SENT_SMS'},
    {'source': '32', 'target': '2', 'label': 'SENT_SMS'},
    {'source': '8', 'target': '21', 'label': 'CALLED'},
    {'source': '4', 'target': '21', 'label': 'SENT_SMS'},
    {'source': '34', 'target': '32', 'label': 'SENT_SMS'},
    {'source': '28', 'target': '40', 'label': 'SENT_SMS'},
    {'source': '35', 'target': '17', 'label': 'SENT_SMS'},
    {'source': '31', 'target': '3', 'label': 'SENT_SMS'},
    {'source': '27', 'target': '45', 'label': 'CALLED'},
    {'source': '42', 'target': '34', 'label': 'CALLED'},
    {'source': '57', 'target': '2', 'label': 'SENT_SMS'},
    {'source': '9', 'target': '46', 'label': 'CALLED'},
    {'source': '47', 'target': '15', 'label': 'SENT_SMS'},
    {'source': '51', 'target': '29', 'label': 'CALLED'}
]

export {baseCustomers, baseLinks, actions}